version: '2'

services:
  # This container builds the httpd config and key files
  # Volume mounted in by other containers
  testfiles:
    build: test/module_test_suite

  # Test Sinatra app which returns the backend request
  testapp:
    build: test/test_sinatra_app

  # Apache2 with module under test
  # Module installed via RPM from rpmbuild container
  httpd:
    build: test/test_httpd
    depends_on:
      - testfiles
      - testapp
    volumes_from:
      - testfiles:ro
    volumes:
      - ./RPMS:/RPMS:ro
    links:
      - testapp
    ports:
      - 80:80

  # Test runner which performs functional tests against httpd
  test_suite:
    build: test/module_test_suite
    depends_on:
      - testfiles
      - httpd
    volumes_from:
      - testfiles:ro
    links:
      - httpd
